### ISSUE TITLE
【已解决】过期项目“手机狂欢城”和“星推官”还在跑

### ISSUE THREAD

**Issue by ChangWeiCat** [chinnkarahoi/jd-scripts-docker#28]
微信一直有这两个项目跑的推送，然后手动跑了一次，确实是有跑

**Comment by chinnkarahoi** [comment]
```sh
git pull
docker-compose up --build --force-recreate --detach jd1
```
照这个更新一下

**Comment by wongweihin** [comment]
同上+1，而且现在重新运行docker-compose build，会卡在
Cloning into '/scripts_tmp'...
疯狂报错
Cloning into '/jd-scripts-docker_tmp'...
Cloning into '/scripts_tmp'...
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://registry.npmjs.org/tunnel failed, reason: connect ECONNREFUSED 104.16.17.35:443
npm ERR!     at ClientRequest.req.on.err (/usr/share/npm/node_modules/node-fetch-npm/src/index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:198:13)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:401:9)
npm ERR!     at TLSSocket.emit (events.js:198:13)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:91:8)
npm ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR!  { FetchError: request to https://registry.npmjs.org/tunnel failed, reason: connect ECONNREFUSED 104.16.17.35:443

**Comment by ChangWeiCat** [comment]
> ```shell
> git pull
> docker-compose up --build --force-recreate --detach jd1
> ```
> 
> 照这个更新一下

谢谢大佬  更新了下   更新的时候确实没有了过期活动
手动跑还是会有（docker exec jd1 bash -c 'set -o allexport; source /all; source /env; source /jd-scripts-docker/resolve.sh; cd /scripts; ls jd_*.js | xargs -i node {}'）

环境洛杉矶vps centos7

![image](https://user-images.githubusercontent.com/62734951/99186871-2b495e80-278e-11eb-9191-3d71eaa89d33.png)
