### ISSUE TITLE
设置了cookie以后出现此错误

### ISSUE THREAD

**Issue by aloasut** [chinnkarahoi/jd-scripts-docker#3]
pt_pin和pt_key用单引号双引号都试过了
测试的时候显示：

🔔京豆签到, 开始!

❗️京豆签到, 错误!
RequestError: connect ECONNREFUSED 0.0.0.0:443
    at ClientRequest.req.once.err (/scripts/node_modules/download/node_modules/got/index.js:182:22)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

🔔京豆签到, 结束! 🕛 6.589 秒

**Comment by chinnkarahoi** [comment]
是一直这样么。
是的话，试一下这个
```sh
docker exec jd1 bash -c 'set -o allexport; source /env; cd /scripts; node jd_bean_sign.js'
```
还有别的log吗，看上去像是网络不太好
