### ISSUE TITLE
手动运行一次全部后，还需要加什么定时任务吗？

### ISSUE THREAD

**Issue by jk9527** [chinnkarahoi/jd-scripts-docker#5]

**Comment by chinnkarahoi** [comment]
不需要加，是根据github action生成的

**Comment by jk9527** [comment]
好的，谢谢
我的有几个错误不知道有没有影响，可以全部跑完，中间看到的这两个错误，node ，request和response检查已安装

let url = $request.url
          ^

ReferenceError: $request is not defined
    at Object.<anonymous> (/scripts/jd_joy_help.js:34:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
/scripts/jd_petTreasureBox.js:23
let body = $response.body
           ^

ReferenceError: $response is not defined
    at Object.<anonymous> (/scripts/jd_petTreasureBox.js:23:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by chinnkarahoi** [comment]
这个是上游脚本的问题，不过应该问题不大

**Comment by jk9527** [comment]
> 这个是上游脚本的问题，不过应该问题不大

ok，就是微信server酱推送，完成不推送吗？只有cookie失效推？已在all里设置

**Comment by chinnkarahoi** [comment]
> > 这个是上游脚本的问题，不过应该问题不大
> 
> ok，就是微信server酱推送，完成不推送吗？只有cookie失效推？已在all里设置

配置好了都会有推送

**Comment by jk9527** [comment]
> > > 这个是上游脚本的问题，不过应该问题不大
> > 
> > 
> > ok，就是微信server酱推送，完成不推送吗？只有cookie失效推？已在all里设置
> 
> 配置好了都会有推送

可以推送了，手动执行的不推，自动后推送正常了

**Comment by chinnkarahoi** [comment]
已修复
