### ISSUE TITLE
签到错误，有没有遇到同样问题的

### ISSUE THREAD

**Issue by jk9527** [chinnkarahoi/jd-scripts-docker#9]
京豆签到, 错误!
RequestError: connect ECONNREFUSED 151.101.228.133:443
    at ClientRequest.req.once.err (/scripts/node_modules/download/node_modules/got/index.js:182:22)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

手动多试几次又能成功，有知道这个ip是干什么的吗？

**Comment by theFool32** [comment]
~同样的错误，请问有解决方案吗~
换了 DNS 好了
